name: formula1_fantasy
description: "A Formula 1 Fantasy app built with Flutter."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0-74.0.dev

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: ^0.20.2

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.9
  shared_preferences: ^2.5.3
  provider: ^6.1.5+1
  sqflite: ^2.4.2
  url_launcher: ^6.3.0
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  flutter_bloc: ^9.1.1
  http: ^1.2.1
  image_picker: ^0.8.4+4
  cached_network_image: ^3.1.0
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4
  supabase_flutter: ^2.10.3
  flutter_native_splash: ^2.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1



flutter_native_splash:
  color: "#7A0000"
  image: "assets/logo2.png"
  android: true
  ios: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo2.png"
  adaptive_icon_background: "#0F0F10"
  adaptive_icon_foreground: "assets/logo2.png"

  android_12:
    color: "#7A0000"
    image: "assets/logo2.png"
    icon_background_color: "#7A0000"

flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/drivers/
    - assets/images/cars/

  fonts:
    - family: TitilliumWeb
      fonts:
        - asset: assets/fonts/TitilliumWeb-Regular.ttf
        - asset: assets/fonts/TitilliumWeb-Bold.ttf
          weight: 700
        - asset: assets/fonts/TitilliumWeb-Light.ttf